* Идея игры
  планету Земля решили посетить инопланетяне. тупые земляне приняли
  контакт за акт агрессии и всячески пытаются отбиваться от
  "захватчиков" несмотря на то, что те даже не пытаются нападать.
* Игровой процесс
  над планетой летает платформа планетарной обороны. нажатие на кнопку
  "выстрел" выпускает самонаводящуюся ракету на захватчиков. попадание
  приносит деньги за которые можно улучшать оборону - усиливать пушки,
  ракеты, покупать дополнительные платформы. постройка и улучшение
  постепенно истощают ресурсы планеты.
* Дерево талантов
** Платформа
*** Вторая платформа
*** Третья платформа
** Ракета
*** Уменьшение кулдауна
*** АОЕ чтоб зацепить окружающие цели
** Наука
*** Возможность вырабатывать ресурсы быстрее.
*** Больше денег за каждую сбитую цель
* Поведение пришельцев
  Летают "птичьим" алгоритмом flock. При попадании - разлетаются в
  стороны, потом снова собираются в стаю. имеют 3 хп. при уничтожении
  одного появляется еще 1 (2 с вероятностью 50%)
** Examples of flock algorithm implementation
  #+begin_quote
  https://codepen.io/andrewlaskey/pen/ElKLz

  https://codepen.io/anuraghazra/pen/qzgazQ

  https://codepen.io/ayamflow/pen/Cpsvd

  #+end_quote
* Конец игры
  после того как ресурсы планеты истощены появляется возможность
  разрушить оборонительные сооружения и из их обломков построить
  ковчег и улететь на другую планету.
* Элементы управления
   +----------------------------------------------+------------------+
   |                /                             | +-----+          |
   |          ---  /                              | +-----+ +-----+  |
   |          ---                                 | +-----+ +-----+  |
   |                                              | +-----+ +-----+  |
   |                                              |         +-----+  |
   |                     --o-                     |  +------------+  |
   |                                              |  |            |  |
   |                   -----------                |  |            |  |
   |                --/           \--             |  |            |  |
   |              -/                 \-           |  +------------+  |
   +--------------/--/-------------\----\---------+----------------------+
   |             |                     |          |                  |
   +--------------\--\-------------/-/-/---/------+------------------------+
